var username = "Muhammad Hunain";
console.log(username);
alert(username);
var age = "15 years old";
console.log(age);
alert(age);
var degree = "Certified Mobile Development";
console.log(degree);
alert(degree);
var pizza = "PIZZA \n PIZZ \n PIZ \n PI \n P";
console.log(pizza);
alert(pizza);
var email = "My email address is example@example.com";
console.log(email);
alert(email);
var detail = "I am trying to learn from the Book A smarter \n way to learn Javascript";
console.log(detail);
alert(detail);
var symbol = "───────── ⋆⋅☆⋅⋆ ──────────";
console.log(symbol);
alert(symbol);
document.write("Yah! I can write HTML content through Javascript");